spring.application.name=survey-service

# --- Database (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/survey_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# --- Server ---
server.port=8080
